repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.11.1
    hooks:
      - id: ansible-lint
        files: ^infra/ansible/
        pass_filenames: false
        args: ["infra/ansible"]

  - repo: local
    hooks:
      - id: gradle-spotless-apply
        name: gradle spotlessApply
        language: system
        pass_filenames: false
        entry: ./gradlew --quiet --no-daemon spotlessApply
        types: [java]
      - id: shfmt
        name: format shell scripts
        language: docker_image
        args: ["-w", "-d", "-i", "2", "-ci"]
        entry: "mvdan/shfmt:v3.12.0-alpine"
        types: [shell]
      - id: shellcheck
        name: analyze shell scripts
        language: docker_image
        entry: "koalaman/shellcheck:v0.11.0"
        types: [shell]
      - id: terraform-fmt-write
        name: terraform fmt
        language: docker_image
        entry: hashicorp/terraform:1.13.4
        args: ["fmt"]
        files: ^.*\.(tf|tfvars|tf\.tmpl)$
