name: CI master - Build

on:
  push:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assemble:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: corretto, java-version: '21'}
      - uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew --no-daemon --build-cache --info clean assemble
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: corretto, java-version: '21'}
      - uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew --no-daemon --build-cache --info clean test
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: corretto, java-version: '21'}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: pre-commit
        run: make requirements && pre-commit run --all

  publish:
    needs: [assemble, test, pre-commit]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with: { distribution: corretto, java-version: '21'}
      - uses: gradle/actions/setup-gradle@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: us-east-1
      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ secrets.ARTIFACT_BUCKET_NAME }}"
      - name: Publish
        run: |
          git config user.name  "${GITHUB_ACTOR} (via CI)"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          ci/scripts/publish-master.sh
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_BUCKET_NAME: ${{ secrets.ARTIFACT_BUCKET_NAME }}

  release:
    needs: [publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with: { distribution: corretto, java-version: '21'}
      - name: Release
        run: |
          ci/scripts/release-version.sh
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
